#ddev-generated
# Simple template to demonstrate rapunzelutils
services:
  rapunzelutils:
    container_name: ddev-${DDEV_SITENAME}-rapunzelutils
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
    - "./aliases.yaml:/etc/aliases.yaml"
